const mongoose=require('mongoose');

const section = mongoose.Schema({
	ProjectName : String,
	sectionName : String,
	count: {type: Number, default: 0},

	userId: String,
	tasks: [{
		comments : String,
		description : String,
		followers: String,	
		projectname: String,
		startDate: String,
		endDate: String,
		sectionname: String,
		taskname: String,
		assigneename: String,
		start: String,
		end: String,
		tags: String,
		uploads: Array,
		userId: String,
		check: {type: Boolean, default: false},
		key: Number,
		children: [{ 
			maintaskname: String,
			taskname: String,
			sectionname: String,
			description: String,
			comments: String,
			followers: String,
			startDate: String,
			endDate: String,
			start: String,
			end: String,
			assigneename: String,
			tags: String,
			uploads: Array,
			userId: String,
			key:  Number,
			check: {type: Boolean, default: false},
			children: [{ 
				maintaskname: String,
				taskname: String,
				subtaskname: String,
				sectionname: String,
				description: String,
				comments: String,
				followers: String,
				startDate: String,
				endDate: String,
				start: String,
				end: String,
				assigneename: String,
				tags: String,
				uploads: Array,
				userId: String,
				key:  Number,
				check: {type: Boolean, default: false},
				children: [{ 
					maintaskname: String,
					taskname: String,
					subtaskname: String,
					subsubtaskname: String,
					sectionname: String,
					description: String,
					comments: String,
					followers: String,
					startDate: String,
					endDate: String,
					start: String,
					end: String,
					assigneename: String,
					tags: String,
					uploads: Array,
					userId: String,
					key:  Number,
					check: {type: Boolean, default: false},
				}]
			}]
		}]
	}],
});

const SectionName = module.exports = mongoose.model('sections',section)